#!/usr/bin/env bash

source lib/vars
source lib/funcs

handle_argument_flags "$@"

source lib/env
source lib/files

log "=========== Starting the script... ==========="

create_missing_env_file

source .env

validate_env_values

copy_files_from_remote
cleanup_old_local_files

log "============ The script is ended! ============"
