#!/usr/bin/env bash

source lib/vars.sh
source lib/funcs.sh

handle_argument_flags "$@"

source lib/env.sh
source lib/files.sh

log "=========== Starting the script... ==========="

create_missing_env_file

source .env

validate_env_values

copy_files_from_remote
cleanup_old_local_files

log "============ The script is ended! ============"
