#!/usr/bin/env bash

handle_argument_flags() {
    case "$1" in
        --silent|-s)
            SHOW_LOG=0
            ;;
        --help|-h)
            echo "$HELP_MESSAGE"
            exit 1
            ;;
    esac
}

log() {
    local level="${2:-INFO}"
    level="${level^^}"
    local emo="ℹ️"

    if [[ "$level" == "ERROR" ]]; then
        emo="❌"
    fi

    output="[$(date +'%Y-%m-%d %H:%M:%S')] [$level] $emo  $1"

    if [[ "$SHOW_LOG" -eq 1 ]]; then
        echo "$output"
    else
        echo "$output" >> "$LOG_FILE"
    fi
}

is_number() {
    if [[ "$1" =~ ^-?[0-9]+$ ]]; then
        return 1
    fi
    return 0
}
